(library
 (name dunolint_engine)
 (public_name dunolint.dunolint_engine)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Base
  -open
  Pplumbing_log
  -open
  Dunolint_stdlib
  -open
  Cmdlang
  -open
  Dunolint.Std)
 (libraries
  base
  cmdlang
  dunolint-lib
  dunolint.dune_linter
  dunolint.dune_project_linter
  dunolint.dunolinter
  dunolint.vendor_prompt
  dunolint_stdlib
  file-rewriter
  logs
  pageantty.git-pager
  pplumbing-log
  sexps-rewriter
  unix)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess no_preprocessing))
