In this test we do some linting based on a config.

Initialize the project root.

  $ touch dune-workspace

Let's create some files.

  $ cat > dune-project <<EOF
  > (lang dune 3.17)
  > 
  > (name my_project_name)
  > EOF

  $ cat > dune <<EOF
  > (library
  >  (name mylib)
  >  (libraries a b c))
  > EOF

  $ mkdir -p _build

  $ cat > _build/dune-project <<EOF
  > (lang dune 3.17)
  > 
  > (name ignored_because_in_build)
  > EOF

  $ mkdir -p vendor

  $ cat > vendor/dune-project <<EOF
  > (lang dune 3.17)
  > 
  > (name my_vendor_project_name)
  > EOF

Currently the behavior of the lint-file command is to not load config files on
its own. See below how the name of the project is not linted:

  $ dunolint lint --yes

If a loaded config is invalid, dunolint will report an error.

  $ printf '(blah)\n' > dunolint

  $ dunolint lint --dry-run -v
  File "dunolint", line 1, characters 0-6:
  1 | (blah)
      ^^^^^^
  Error: Dunolint config expected to start with (lang dunolint VERSION).
  dunolint: [INFO] Skipping directory due to invalid config: "./"
  [123]

This would also apply when loading invalid parent config via discovery.

  $ dunolint lint --dry-run -v --below vendor/
  File "dunolint", line 1, characters 0-6:
  1 | (blah)
      ^^^^^^
  Error: Dunolint config expected to start with (lang dunolint VERSION).
  [123]

Unsupported config versions are reported with a located error message.

  $ printf '((version 101101)(blah))\n' > dunolint

  $ dunolint lint --yes
  File "dunolint", line 1, characters 0-24:
  1 | ((version 101101)(blah))
      ^^^^^^^^^^^^^^^^^^^^^^^^
  Error: Dunolint config expected to start with (lang dunolint VERSION).
  [123]

  $ printf '(lang dunolint 101101)\n' > dunolint

  $ dunolint lint --yes
  File "dunolint", line 1, characters 15-21:
  1 | (lang dunolint 101101)
                     ^^^^^^
  Error: Unsupported dunolint config version [101101].
  [123]

If there are no rules, the linting will succeed but does nothing in this case.

  $ printf '(lang dunolint 1.0)\n' > dunolint

  $ dunolint lint --yes

Now let's load a config. To make it easier to write in this test, we're
generating an actual config from an OCaml file.

  $ ./lint_file_config_gen.exe --format=v1 > dunolint

  $ cat dunolint
  ;; This file is generated by [bin/lint_file_gen_config.ml]. Do not edit!
  (lang dunolint 1.0)
  
  (skip_paths .git/*)
  
  (skip_paths _build/*)
  
  (rule
   (cond ((path (glob vendor/*)) return)
    (true (enforce (dune_project (name (equals foo)))))))

Let's lint with this config.

  $ dunolint lint --dry-run
  dry-run: Would edit file "dune-project":
  -1,3 +1,3
    (lang dune 3.17)
    
  -|(name my_project_name)
  +|(name foo)

Let's exercise a case where the file is specifically ignored by the config.

  $ cat > dunolint <<EOF
  > (lang dunolint 1.0)
  > (skip_paths dune-project)
  > EOF

  $ dunolint lint --dry-run
