(library
 (name dune_project_linter_test)
 (package dunolint-tests)
 (inline_tests)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Base
  -open
  Dunolint_stdlib
  -open
  Dunolint.Std)
 (libraries
  base
  dune_project_linter
  dunolint
  dunolint_stdlib
  dunolinter
  file-rewriter
  parsexp
  sexps-rewriter
  test_helpers)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess
  (pps ppx_expect ppx_sexp_value)))
