(***************************************************************************************)
(*  Dunolint_stdlib - Extending OCaml's Stdlib for Dunolint                            *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>        *)
(*  SPDX-License-Identifier: MIT OR LGPL-3.0-or-later WITH LGPL-3.0-linking-exception  *)
(***************************************************************************************)

(* Acknowledgement: this test file was generated by Claude (Anthropic, model
   claude-opus-4-7, 1M context) and reviewed by the author. *)

let%expect_test "sexp round-trip" =
  let test s =
    let sexp = String.sexp_of_t s in
    let s' = String.t_of_sexp sexp in
    require_equal (module String) s s'
  in
  test "";
  [%expect {||}];
  test "hello";
  [%expect {||}];
  test "with spaces and \"quotes\"";
  [%expect {||}];
  ()
;;

let%expect_test "is_empty" =
  let test s = print_dyn (Dyn.pair Dyn.string Dyn.bool (s, String.is_empty s)) in
  test "";
  [%expect {| ("", true) |}];
  test " ";
  [%expect {| (" ", false) |}];
  test "x";
  [%expect {| ("x", false) |}];
  ()
;;

let%expect_test "is_prefix" =
  let test t ~prefix =
    print_dyn (Dyn.pair Dyn.string Dyn.bool (t, String.is_prefix t ~prefix))
  in
  test "" ~prefix:"";
  [%expect {| ("", true) |}];
  test "abc" ~prefix:"";
  [%expect {| ("abc", true) |}];
  test "abc" ~prefix:"ab";
  [%expect {| ("abc", true) |}];
  test "abc" ~prefix:"abc";
  [%expect {| ("abc", true) |}];
  test "abc" ~prefix:"abcd";
  [%expect {| ("abc", false) |}];
  test "abc" ~prefix:"bc";
  [%expect {| ("abc", false) |}];
  test "" ~prefix:"a";
  [%expect {| ("", false) |}];
  ()
;;

let%expect_test "is_suffix" =
  let test t ~suffix =
    print_dyn (Dyn.pair Dyn.string Dyn.bool (t, String.is_suffix t ~suffix))
  in
  test "" ~suffix:"";
  [%expect {| ("", true) |}];
  test "abc" ~suffix:"";
  [%expect {| ("abc", true) |}];
  test "abc" ~suffix:"bc";
  [%expect {| ("abc", true) |}];
  test "abc" ~suffix:"abc";
  [%expect {| ("abc", true) |}];
  test "abc" ~suffix:"zabc";
  [%expect {| ("abc", false) |}];
  test "abc" ~suffix:"ab";
  [%expect {| ("abc", false) |}];
  test "" ~suffix:"a";
  [%expect {| ("", false) |}];
  ()
;;

let%expect_test "chop_prefix" =
  let test t ~prefix = print_dyn (Dyn.option Dyn.string (String.chop_prefix t ~prefix)) in
  test "abc" ~prefix:"";
  [%expect {| Some "abc" |}];
  test "abc" ~prefix:"ab";
  [%expect {| Some "c" |}];
  test "abc" ~prefix:"abc";
  [%expect {| Some "" |}];
  test "abc" ~prefix:"abcd";
  [%expect {| None |}];
  test "abc" ~prefix:"bc";
  [%expect {| None |}];
  test "" ~prefix:"";
  [%expect {| Some "" |}];
  test "" ~prefix:"a";
  [%expect {| None |}];
  ()
;;

let%expect_test "chop_suffix" =
  let test t ~suffix = print_dyn (Dyn.option Dyn.string (String.chop_suffix t ~suffix)) in
  test "abc" ~suffix:"";
  [%expect {| Some "abc" |}];
  test "abc" ~suffix:"bc";
  [%expect {| Some "a" |}];
  test "abc" ~suffix:"abc";
  [%expect {| Some "" |}];
  test "abc" ~suffix:"zabc";
  [%expect {| None |}];
  test "abc" ~suffix:"ab";
  [%expect {| None |}];
  test "" ~suffix:"";
  [%expect {| Some "" |}];
  test "" ~suffix:"a";
  [%expect {| None |}];
  ()
;;

let%expect_test "lsplit2" =
  let test t ~on =
    print_dyn (Dyn.option (Dyn.pair Dyn.string Dyn.string) (String.lsplit2 t ~on))
  in
  test "" ~on:'.';
  [%expect {| None |}];
  test "no-separator" ~on:'.';
  [%expect {| None |}];
  test "a.b" ~on:'.';
  [%expect {| Some ("a", "b") |}];
  (* Splits on the first occurrence. *)
  test "a.b.c" ~on:'.';
  [%expect {| Some ("a", "b.c") |}];
  test ".b" ~on:'.';
  [%expect {| Some ("", "b") |}];
  test "a." ~on:'.';
  [%expect {| Some ("a", "") |}];
  test "." ~on:'.';
  [%expect {| Some ("", "") |}];
  ()
;;

let%expect_test "split" =
  let test t ~on = print_dyn (Dyn.list Dyn.string (String.split t ~on)) in
  test "" ~on:'.';
  [%expect {| [ "" ] |}];
  test "no-separator" ~on:'.';
  [%expect {| [ "no-separator" ] |}];
  test "a.b.c" ~on:'.';
  [%expect {| [ "a"; "b"; "c" ] |}];
  test ".a.b" ~on:'.';
  [%expect {| [ ""; "a"; "b" ] |}];
  test "a.b." ~on:'.';
  [%expect {| [ "a"; "b"; "" ] |}];
  test ".." ~on:'.';
  [%expect {| [ ""; ""; "" ] |}];
  ()
;;

let%expect_test "of_char_list" =
  let test cs = print_dyn (Dyn.string (String.of_char_list cs)) in
  test [];
  [%expect {| "" |}];
  test [ 'h'; 'e'; 'l'; 'l'; 'o' ];
  [%expect {| "hello" |}];
  test [ 'a' ];
  [%expect {| "a" |}];
  test [ '\000'; '\001'; '\255' ];
  [%expect {| "\000\001\255" |}];
  ()
;;

let%expect_test "to_string" =
  print_dyn (Dyn.string (String.to_string ""));
  [%expect {| "" |}];
  print_dyn (Dyn.string (String.to_string "hello"));
  [%expect {| "hello" |}];
  (* Identity at the value level. *)
  let s = "abc" in
  require (phys_equal s (String.to_string s));
  [%expect {||}];
  ()
;;

let%expect_test "lstrip - default drop" =
  let test s = print_dyn (Dyn.string (String.lstrip s)) in
  test "";
  [%expect {| "" |}];
  test "   ";
  [%expect {| "" |}];
  test "  hello";
  [%expect {| "hello" |}];
  test "hello  ";
  [%expect {| "hello  " |}];
  test "  hello  ";
  [%expect {| "hello  " |}];
  test "\t\n\r hello";
  [%expect {| "hello" |}];
  test "no-leading";
  [%expect {| "no-leading" |}];
  ()
;;

let%expect_test "rstrip - default drop" =
  let test s = print_dyn (Dyn.string (String.rstrip s)) in
  test "";
  [%expect {| "" |}];
  test "   ";
  [%expect {| "" |}];
  test "hello  ";
  [%expect {| "hello" |}];
  test "  hello";
  [%expect {| "  hello" |}];
  test "  hello  ";
  [%expect {| "  hello" |}];
  test "hello \t\n\r";
  [%expect {| "hello" |}];
  test "no-trailing";
  [%expect {| "no-trailing" |}];
  ()
;;

let%expect_test "strip - default drop" =
  let test s = print_dyn (Dyn.string (String.strip s)) in
  test "";
  [%expect {| "" |}];
  test "   ";
  [%expect {| "" |}];
  test "  hello  ";
  [%expect {| "hello" |}];
  test "\t\n hello \r\n";
  [%expect {| "hello" |}];
  test "hello";
  [%expect {| "hello" |}];
  ()
;;

let%expect_test "lstrip / rstrip / strip - custom drop" =
  let drop = function
    | 'x' | 'y' -> true
    | _ -> false
  in
  print_dyn (Dyn.string (String.lstrip ~drop "xxxhelloxxx"));
  [%expect {| "helloxxx" |}];
  print_dyn (Dyn.string (String.rstrip ~drop "xxxhelloxxx"));
  [%expect {| "xxxhello" |}];
  print_dyn (Dyn.string (String.strip ~drop "xyxhelloxyx"));
  [%expect {| "hello" |}];
  print_dyn (Dyn.string (String.strip ~drop "xyxxyx"));
  [%expect {| "" |}];
  (* Default whitespace is not stripped when a custom [drop] is given. *)
  print_dyn (Dyn.string (String.strip ~drop "  xhellox  "));
  [%expect {| "  xhellox  " |}];
  ()
;;
