(***************************************************************************************)
(*  Dunolint_stdlib - Extending OCaml's Stdlib for Dunolint                            *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>        *)
(*  SPDX-License-Identifier: MIT OR LGPL-3.0-or-later WITH LGPL-3.0-linking-exception  *)
(***************************************************************************************)

(* Acknowledgement: this test file was generated by Claude (Anthropic, model
   claude-opus-4-7, 1M context) and reviewed by the author. *)

let%expect_test "bind" =
  print_dyn
    (Dyn.option Dyn.int (Option.bind None ~f:(fun _ -> (assert false [@coverage off]))));
  [%expect {| None |}];
  print_dyn (Dyn.option Dyn.int (Option.bind (Some 3) ~f:(fun x -> Some (x * x))));
  [%expect {| Some 9 |}];
  print_dyn (Dyn.option Dyn.int (Option.bind (Some 3) ~f:(fun _ -> None)));
  [%expect {| None |}];
  ()
;;

let%expect_test "exists" =
  require (not (Option.exists None ~f:(fun _ -> (assert false [@coverage off]))));
  require (Option.exists (Some 42) ~f:(fun i -> Int.equal i 42));
  require (not (Option.exists (Some 0) ~f:(fun i -> Int.equal i 42)));
  [%expect {||}];
  ()
;;

let%expect_test "iter - None" =
  Option.iter None ~f:(fun _ -> (assert false [@coverage off]));
  [%expect {||}];
  ()
;;

let%expect_test "iter - Some" =
  Option.iter (Some 42) ~f:(fun i -> print_dyn (Dyn.int i));
  [%expect {| 42 |}];
  ()
;;

let%expect_test "map - None" =
  print_dyn
    (Dyn.option Dyn.int (Option.map None ~f:(fun _ -> (assert false [@coverage off]))));
  [%expect {| None |}];
  ()
;;

let%expect_test "map - Some" =
  print_dyn (Dyn.option Dyn.int (Option.map (Some 3) ~f:(fun x -> x * x)));
  [%expect {| Some 9 |}];
  ()
;;

let%expect_test "value_map - None uses default" =
  print_dyn
    (Dyn.int
       (Option.value_map None ~default:0 ~f:(fun _ -> (assert false [@coverage off]))));
  [%expect {| 0 |}];
  ()
;;

let%expect_test "value_map - Some applies f" =
  print_dyn (Dyn.int (Option.value_map (Some 5) ~default:0 ~f:(fun x -> x + 100)));
  [%expect {| 105 |}];
  ()
;;
