(***************************************************************************************)
(*  Dunolint_stdlib - Extending OCaml's Stdlib for Dunolint                            *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>        *)
(*  SPDX-License-Identifier: MIT OR LGPL-3.0-or-later WITH LGPL-3.0-linking-exception  *)
(***************************************************************************************)

(* Acknowledgement: this test file was generated by Claude (Anthropic, model
   claude-opus-4-7, 1M context) and reviewed by the author. *)

let%expect_test "read_all - empty file" =
  Out_channel.write_all "empty.txt" ~data:"";
  print_dyn (Dyn.string (In_channel.read_all "empty.txt"));
  [%expect {| "" |}];
  ()
;;

let%expect_test "read_all - small file" =
  Out_channel.write_all "small.txt" ~data:"hello, world\n";
  print_dyn (Dyn.string (In_channel.read_all "small.txt"));
  [%expect
    {|
    "hello, world\n\
     "
    |}];
  ()
;;

let%expect_test "read_all - binary content with NULs" =
  let data = "ab\000cd\000ef" in
  Out_channel.write_all "binary.bin" ~data;
  let read = In_channel.read_all "binary.bin" in
  require_equal (module Int) (String.length read) (String.length data);
  [%expect {||}];
  require (String.equal read data);
  [%expect {||}];
  ()
;;

let%expect_test "input_all - from open channel" =
  Out_channel.write_all "input_all.txt" ~data:"line1\nline2\n";
  let contents = In_channel.with_open_text "input_all.txt" In_channel.input_all in
  print_dyn (Dyn.string contents);
  [%expect
    {|
    "line1\n\
     line2\n\
     "
    |}];
  ()
;;

let%expect_test "read_all - missing file raises" =
  require_does_raise (fun () -> In_channel.read_all "does-not-exist.txt");
  [%expect {| (Sys_error "does-not-exist.txt: No such file or directory") |}];
  ()
;;
