(***************************************************************************************)
(*  Dunolint_stdlib - Extending OCaml's Stdlib for Dunolint                            *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>        *)
(*  SPDX-License-Identifier: MIT OR LGPL-3.0-or-later WITH LGPL-3.0-linking-exception  *)
(***************************************************************************************)

(* Acknowledgement: this test file was generated by Claude (Anthropic, model
   claude-opus-4-7, 1M context) and reviewed by the author. *)

let dyn_char c = Dyn.string (Char.to_string c)

let%expect_test "is_alphanum" =
  let test c = print_dyn (Dyn.pair dyn_char Dyn.bool (c, Char.is_alphanum c)) in
  test 'a';
  [%expect {| ("a", true) |}];
  test 'Z';
  [%expect {| ("Z", true) |}];
  test '0';
  [%expect {| ("0", true) |}];
  test '9';
  [%expect {| ("9", true) |}];
  test '_';
  [%expect {| ("_", false) |}];
  test '-';
  [%expect {| ("-", false) |}];
  test ' ';
  [%expect {| (" ", false) |}];
  test '\000';
  [%expect {| ("\000", false) |}];
  test '\127';
  [%expect {| ("\127", false) |}];
  ()
;;

let%expect_test "is_whitespace" =
  let test c = print_dyn (Dyn.pair dyn_char Dyn.bool (c, Char.is_whitespace c)) in
  test ' ';
  [%expect {| (" ", true) |}];
  test '\t';
  [%expect {| ("\t", true) |}];
  test '\n';
  [%expect
    {|
    ("\n\
      ", true)
    |}];
  test '\r';
  [%expect {| ("\r", true) |}];
  test '\011';
  [%expect {| ("\011", true) |}];
  test '\012';
  [%expect {| ("\012", true) |}];
  test 'a';
  [%expect {| ("a", false) |}];
  test '\000';
  [%expect {| ("\000", false) |}];
  test '_';
  [%expect {| ("_", false) |}];
  ()
;;

let%expect_test "is_uppercase_ascii" =
  let test c = print_dyn (Dyn.pair dyn_char Dyn.bool (c, Char.is_uppercase_ascii c)) in
  test 'A';
  [%expect {| ("A", true) |}];
  test 'Z';
  [%expect {| ("Z", true) |}];
  test 'a';
  [%expect {| ("a", false) |}];
  test 'z';
  [%expect {| ("z", false) |}];
  test '0';
  [%expect {| ("0", false) |}];
  test ' ';
  [%expect {| (" ", false) |}];
  test '\000';
  [%expect {| ("\000", false) |}];
  ()
;;

let%expect_test "to_string" =
  let test c = print_dyn (Dyn.string (Char.to_string c)) in
  test 'a';
  [%expect {| "a" |}];
  test 'Z';
  [%expect {| "Z" |}];
  test '0';
  [%expect {| "0" |}];
  test ' ';
  [%expect {| " " |}];
  test '\n';
  [%expect
    {|
    "\n\
     "
    |}];
  test '\000';
  [%expect {| "\000" |}];
  require_equal (module Int) 1 (String.length (Char.to_string 'x'));
  [%expect {||}];
  ()
;;
