(***************************************************************************************)
(*  Dunolint_stdlib - Extending OCaml's Stdlib for Dunolint                            *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>        *)
(*  SPDX-License-Identifier: MIT OR LGPL-3.0-or-later WITH LGPL-3.0-linking-exception  *)
(***************************************************************************************)

(* Acknowledgement: this test file was generated by Claude (Anthropic, model
   claude-opus-4-7, 1M context) and reviewed by the author. *)

let%expect_test "write_all - simple round-trip" =
  Out_channel.write_all "simple.txt" ~data:"abc";
  print_dyn (Dyn.string (In_channel.read_all "simple.txt"));
  [%expect {| "abc" |}];
  ()
;;

let%expect_test "write_all - overwrites existing file" =
  Out_channel.write_all "overwrite.txt" ~data:"first contents";
  Out_channel.write_all "overwrite.txt" ~data:"second";
  print_dyn (Dyn.string (In_channel.read_all "overwrite.txt"));
  [%expect {| "second" |}];
  ()
;;

let%expect_test "create - default flags overwrite the file" =
  Out_channel.write_all "create.txt" ~data:"original";
  let oc = Out_channel.create "create.txt" in
  Out_channel.output_string oc "new";
  Out_channel.close oc;
  print_dyn (Dyn.string (In_channel.read_all "create.txt"));
  [%expect {| "new" |}];
  ()
;;

let%expect_test "create - append flag" =
  Out_channel.write_all "append.txt" ~data:"hello";
  let oc = Out_channel.create ~append:true "append.txt" in
  Out_channel.output_string oc ", world";
  Out_channel.close oc;
  print_dyn (Dyn.string (In_channel.read_all "append.txt"));
  [%expect {| "hello, world" |}];
  ()
;;

let%expect_test "with_file - closes the channel on success" =
  Out_channel.with_file "with_file.txt" ~f:(fun oc -> Out_channel.output_string oc "abc");
  print_dyn (Dyn.string (In_channel.read_all "with_file.txt"));
  [%expect {| "abc" |}];
  ()
;;

let%expect_test "with_file - closes the channel even if [f] raises" =
  require_does_raise (fun () ->
    Out_channel.with_file "raise.txt" ~f:(fun oc ->
      Out_channel.output_string oc "partial";
      failwith "boom"));
  [%expect {| (Failure boom) |}];
  (* The data written before the exception should still be flushed. *)
  print_dyn (Dyn.string (In_channel.read_all "raise.txt"));
  [%expect {| "partial" |}];
  ()
;;

let%expect_test "with_file - both [f] and close raise: both errors reported" =
  require_does_raise (fun () ->
    Out_channel.with_file "double-raise.txt" ~f:(fun oc ->
      Out_channel.output_string oc "data";
      (* Invalidate the underlying fd so the subsequent flush fails. *)
      Unix.close (Unix.descr_of_out_channel oc);
      failwith "user-boom"));
  [%expect
    {|
    ("Out_channel.with_file failed." (user (Failure user-boom))
     (close (Sys_error "Bad file descriptor")))
    |}];
  ()
;;

let%expect_test "newline" =
  Out_channel.with_file "newline.txt" ~f:(fun oc ->
    Out_channel.output_string oc "a";
    Out_channel.newline oc;
    Out_channel.output_string oc "b");
  print_dyn (Dyn.string (In_channel.read_all "newline.txt"));
  [%expect
    {|
    "a\n\
     b"
    |}];
  ()
;;

let%expect_test "output_line" =
  Out_channel.with_file "output_line.txt" ~f:(fun oc ->
    Out_channel.output_line oc "first";
    Out_channel.output_line oc "second");
  print_dyn (Dyn.string (In_channel.read_all "output_line.txt"));
  [%expect
    {|
    "first\n\
     second\n\
     "
    |}];
  ()
;;

let%expect_test "output_line - empty string still emits newline" =
  Out_channel.with_file "empty_line.txt" ~f:(fun oc -> Out_channel.output_line oc "");
  print_dyn (Dyn.string (In_channel.read_all "empty_line.txt"));
  [%expect
    {|
    "\n\
     "
    |}];
  ()
;;
