(library
 (name dunolint_cli)
 (package dunolint)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Pplumbing_log
  -open
  Pplumbing_log_cli
  -open
  Dunolint_stdlib
  -open
  Cmdlang
  -open
  Dunolint.Std)
 (libraries
  cmdlang
  dune_linter
  dune_project_linter
  dune_workspace_linter
  dunolint-lib
  dunolint_engine
  dunolint_linter
  dunolint_stdlib
  dunolinter
  parsexp
  pplumbing-log
  pplumbing-log-cli
  sexps-rewriter
  unix)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess no_preprocessing))
